name: Secret Check

on:
  push:
  pull_request:

jobs:
  secrets-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install
          cd ..
          git secrets --install
          git secrets --add 'GITHUB_TOKEN'
          git secrets --scan
