name: Secret Check

on:
  push:
  pull_request:

jobs:
  secrets-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install
          cd ..
          git secrets --install

      - name: Allow False Positives
        run: |
          echo ".env.example:GITHUB_TOKEN" >> .gitallowed
          echo "README.md:GITHUB_TOKEN" >> .gitallowed
          echo ".github/workflows/:GITHUB_TOKEN" >> .gitallowed
          git secrets --add-provider -- cat .gitallowed

      - name: Run git-secrets Scan
        run: git secrets --scan
